### ISSUE TITLE
Converse.js has working OMEMO

### ISSUE THREAD

**Issue by allo-** [bascht/omemo-top#126] opened 2018-09-17 18:01 UTC
OMEMO https://github.com/conversejs/converse.js/issues/497 was implemented in https://github.com/conversejs/converse.js/releases/tag/v4.0.0

**Comment by devurandom** [comment] 2018-09-18 06:50
Duplicate of #124

**Comment by bascht** [comment] 2018-09-18 07:20
And already merged via #121 :smile:

**Closed by bascht** 2018-09-18 07:20 UTC
